INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Adele', 'British', 'Someone Like You');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Akon', 'Senegalese', 'Dont Matter');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Backstreet Boys', 'American', 'I Want It That Way');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Dave', 'British', 'Location');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Drake', 'Canadian', 'One Dance');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Ed Sheeran', 'British', 'Shape of You');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Kanye West', 'American', 'Homecoming');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Lil Baby', 'American', 'Freestyle');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Pop Smoke', 'American', 'Dior');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('Shakira', 'Colombian', 'Hips Dont Lie');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('50 Cent', 'American', 'Many Men');
INSERT INTO artists (artist_name, nationality, biggest_hit) VALUES ('2pac', 'American', 'Hail Mary');